# Generated by Django 5.2 on 2025-04-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_collaborationgroup_members_remove_task_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
