# Generated by Django 5.1.7 on 2025-04-03 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ISSUE_CREATED', 'Issue Created'), ('ISSUE_ASSIGNED', 'Issue Assigned'), ('STATUS_UPDATED', 'Status Updated'), ('COMMENT_ADDED', 'Comment Added'), ('ISSUE_ESCALATED', 'Issue Escalated')], default='ISSUE_CREATED', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', 'created_at'], name='notificatio_user_id_90f4cc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='notificatio_content_702c56_idx'),
        ),
    ]
